server:
  port: 1111
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MahmoudFawzyKhalil/spring-cloud-config-server-files
          search-paths:
            - station*
          repos:
            performance-testing:
              pattern: '*/perf'
              uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls-perf-2
              search-paths:
                - station*