server:
  port: 1111
encrypt:
  key: ABCDEFG
spring:
  cloud:
    config:
      server:
        encrypt:
          enabled: false
        git:
          uri: https://github.com/MahmoudFawzyKhalil/spring-cloud-config-server-files
          search-paths:
            - station*
          repos:
            performance-testing:
              pattern: '*/perf'
              uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls-perf-2
              search-paths:
                - station*
  security:
    user:
      name: mahmoud
      password: fawzy